# Generated by Django 4.2.3 on 2023-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='desciption',
        ),
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
